import * as path from "node:path";
import { fileURLToPath } from "node:url";

import * as cdk from "aws-cdk-lib";
import * as acm from "aws-cdk-lib/aws-certificatemanager";
import * as cloudfront from "aws-cdk-lib/aws-cloudfront";
import * as origins from "aws-cdk-lib/aws-cloudfront-origins";
import * as dynamodb from "aws-cdk-lib/aws-dynamodb";
import * as apigwv2 from "aws-cdk-lib/aws-apigatewayv2";
import * as integrations from "aws-cdk-lib/aws-apigatewayv2-integrations";
import * as iam from "aws-cdk-lib/aws-iam";
import * as kms from "aws-cdk-lib/aws-kms";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as logs from "aws-cdk-lib/aws-logs";
import * as route53 from "aws-cdk-lib/aws-route53";
import * as targets from "aws-cdk-lib/aws-route53-targets";
import * as secretsmanager from "aws-cdk-lib/aws-secretsmanager";
import * as s3 from "aws-cdk-lib/aws-s3";
import * as s3deploy from "aws-cdk-lib/aws-s3-deployment";
import * as cr from "aws-cdk-lib/custom-resources";
import type { Construct } from "constructs";

import { authHost, issuerUrl, type AuthConfig } from "../../config/types.js";

const dir = path.dirname(fileURLToPath(import.meta.url));

export interface AuthAppStackProps extends cdk.StackProps {
  hostedZone: route53.IHostedZone;
  table: dynamodb.TableV2;
  signingKey: kms.Key;
}

/**
 * The replaceable application tier: ACM cert, the Rust Lambda, the HTTP API,
 * the SPA bucket, and the CloudFront distribution that serves both the SPA and
 * the API on `auth.ericminassian.com`.
 */
export class AuthAppStack extends cdk.Stack {
  constructor(scope: Construct, id: string, config: AuthConfig, props: AuthAppStackProps) {
    super(scope, id, props);
    const host = authHost(config);
    const lambdaAssetPath = path.join(dir, "../..", config.lambdaAssetPath);

    // --- TLS certificate (us-east-1, DNS-validated in our zone) ---
    const certificate = new acm.Certificate(this, "Certificate", {
      domainName: host,
      validation: acm.CertificateValidation.fromDns(props.hostedZone),
    });

    // --- Origin-lock shared secret ---
    // The Rust backend rejects any /api or /oauth request whose `x-origin-verify`
    // header doesn't equal ORIGIN_VERIFY_SECRET. CloudFront stamps that header on
    // every request to the API origin (see `apiOrigin` below), so only traffic
    // routed through the distribution reaches the API; direct hits on the public
    // execute-api endpoint are rejected. That's what stops an attacker from
    // bypassing CloudFront and spoofing the otherwise tamper-proof
    // CloudFront-Viewer-Address / CloudFront-Viewer-ASN headers to defeat the
    // per-IP / per-ASN rate limits.
    //
    // Generated by Secrets Manager so it can be rotated. TRADEOFF: the value is
    // pushed into both the Lambda env var and the CloudFront origin header as a
    // `{{resolve:secretsmanager:...}}` dynamic reference that CloudFormation
    // resolves at deploy time. A CloudFront custom-header value is stored in the
    // distribution config as plaintext once deployed regardless, and the Lambda
    // needs the literal at runtime, so materializing it at synth is inherent to
    // the mechanism — the Secret resource stays the single source of truth and
    // rotation point. `unsafeUnwrap()` is required because the
    // `@aws-cdk/core:checkSecretUsage` feature flag (cdk.json) otherwise refuses
    // to stringify a SecretValue into a template property.
    const originVerifySecret = new secretsmanager.Secret(this, "OriginVerifySecret", {
      generateSecretString: {
        // No punctuation → a clean, RFC-7230-safe HTTP header token value.
        excludePunctuation: true,
        passwordLength: 64,
      },
    });
    const originVerifyValue = originVerifySecret.secretValue.unsafeUnwrap();

    // --- Rust Lambda (Lambdalith) ---
    const fn = new lambda.Function(this, "Api", {
      runtime: lambda.Runtime.PROVIDED_AL2023,
      handler: "bootstrap",
      code: lambda.Code.fromAsset(lambdaAssetPath),
      architecture: lambda.Architecture.ARM_64,
      memorySize: 256,
      timeout: cdk.Duration.seconds(10),
      environment: {
        TABLE_NAME: props.table.tableName,
        ISSUER: issuerUrl(config),
        KMS_KEY_ID: props.signingKey.keyId,
        ORIGIN_VERIFY_SECRET: originVerifyValue,
        RUST_LOG: "info",
      },
      logGroup: new logs.LogGroup(this, "ApiLogs", {
        retention: logs.RetentionDays.THREE_MONTHS,
        removalPolicy: cdk.RemovalPolicy.DESTROY,
      }),
    });
    props.table.grantReadWriteData(fn);
    props.signingKey.grant(fn, "kms:Sign", "kms:GetPublicKey");

    // --- HTTP API in front of the Lambda ---
    const httpApi = new apigwv2.HttpApi(this, "HttpApi", {
      defaultIntegration: new integrations.HttpLambdaIntegration("DefaultIntegration", fn),
    });
    const stage = httpApi.defaultStage?.node.defaultChild as apigwv2.CfnStage;
    stage.defaultRouteSettings = {
      throttlingRateLimit: 25,
      throttlingBurstLimit: 50,
    };

    // --- SPA bucket (private, served via CloudFront OAC) ---
    const spaBucket = new s3.Bucket(this, "SpaBucket", {
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    // --- CloudFront distribution ---
    const apiOrigin = new origins.HttpOrigin(
      `${httpApi.apiId}.execute-api.${this.region}.amazonaws.com`,
      {
        protocolPolicy: cloudfront.OriginProtocolPolicy.HTTPS_ONLY,
        // Origin-lock header — proves to the backend that a request arrived via
        // CloudFront. Must stay in lockstep with the Lambda's ORIGIN_VERIFY_SECRET
        // (same generated secret), and the name must match the header the Rust
        // middleware checks exactly: `x-origin-verify`.
        customHeaders: { "x-origin-verify": originVerifyValue },
      },
    );
    // Forward cookies, query strings, and the headers the API needs — plus
    // CloudFront-Viewer-Address, the tamper-proof source IP the service uses
    // for rate limiting (the leftmost X-Forwarded-For is client-spoofable), and
    // CloudFront-Viewer-ASN, the equally tamper-proof source network the
    // service uses for per-ASN rate limiting. Host is omitted (execute-api
    // rejects a foreign Host). Authorization can't be listed in an
    // origin-request policy; the one endpoint that needs it (/oauth/userinfo,
    // Bearer) gets its own behavior below using the managed ALL_VIEWER policy,
    // which forwards Authorization automatically.
    const apiOriginRequestPolicy = new cloudfront.OriginRequestPolicy(
      this,
      "ApiOriginRequestPolicy",
      {
        cookieBehavior: cloudfront.OriginRequestCookieBehavior.all(),
        queryStringBehavior: cloudfront.OriginRequestQueryStringBehavior.all(),
        // CloudFront caps an origin-request policy at 10 forwarded headers, so
        // this list must stay at or below 10. Only headers the backend actually
        // reads are forwarded: the CSRF check uses Origin + Sec-Fetch-Site (not
        // -Mode/-Dest, which were dropped to make room), rate limiting uses the
        // Viewer-Address/ASN, the session list uses User-Agent + Viewer-Country.
        headerBehavior: cloudfront.OriginRequestHeaderBehavior.allowList(
          "CloudFront-Viewer-Address",
          "CloudFront-Viewer-ASN",
          // Coarse country for the account page's "where you're signed in"
          // session list (country only — never the IP).
          "CloudFront-Viewer-Country",
          "Origin",
          "Content-Type",
          "Accept",
          "Referer",
          "User-Agent",
          "Sec-Fetch-Site",
        ),
      },
    );
    // Security headers for the API / OIDC / metadata surface. Deliberately
    // omits frameOptions / frame-ancestors so /oauth/authorize stays iframe-able
    // for the SDK's prompt=none silent-auth flow (the SPA's own policy below
    // keeps DENY). HSTS is host-scoped so this mainly backstops non-SPA paths.
    const apiSecurity = new cloudfront.ResponseHeadersPolicy(this, "ApiSecurityHeaders", {
      securityHeadersBehavior: {
        strictTransportSecurity: {
          accessControlMaxAge: cdk.Duration.days(365),
          includeSubdomains: true,
          preload: true,
          override: true,
        },
        contentTypeOptions: { override: true },
        referrerPolicy: {
          referrerPolicy: cloudfront.HeadersReferrerPolicy.NO_REFERRER,
          override: true,
        },
      },
    });
    const apiBehavior: cloudfront.BehaviorOptions = {
      origin: apiOrigin,
      viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
      allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
      cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
      originRequestPolicy: apiOriginRequestPolicy,
      responseHeadersPolicy: apiSecurity,
    };
    // For JWKS/discovery: cache at the edge per the origin's Cache-Control, but
    // do NOT key on (and thus forward) Host — the managed
    // UseOriginCacheControlHeaders policy whitelists Host, which execute-api
    // rejects. This custom policy keeps the TTLs unset (origin-driven) and an
    // empty key.
    const wellKnownCachePolicy = new cloudfront.CachePolicy(this, "WellKnownCachePolicy", {
      headerBehavior: cloudfront.CacheHeaderBehavior.none(),
      cookieBehavior: cloudfront.CacheCookieBehavior.none(),
      queryStringBehavior: cloudfront.CacheQueryStringBehavior.none(),
    });
    // userinfo is Bearer-authenticated, so it needs Authorization forwarded
    // (and doesn't need the viewer IP — it isn't IP rate-limited).
    const bearerBehavior: cloudfront.BehaviorOptions = {
      origin: apiOrigin,
      viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
      allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
      cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
      originRequestPolicy: cloudfront.OriginRequestPolicy.ALL_VIEWER_EXCEPT_HOST_HEADER,
      responseHeadersPolicy: apiSecurity,
    };

    // SPA client-side routing: rewrite extensionless paths to /index.html.
    // Only attached to the default (SPA) behavior, so it never touches the
    // extensionless API/OIDC paths, which match their own behaviors first.
    const spaRewrite = new cloudfront.Function(this, "SpaRewrite", {
      runtime: cloudfront.FunctionRuntime.JS_2_0,
      code: cloudfront.FunctionCode.fromInline(
        "function handler(event){var r=event.request;if(r.uri.indexOf('.')===-1){r.uri='/index.html';}return r;}",
      ),
    });

    const spaSecurity = new cloudfront.ResponseHeadersPolicy(this, "SpaSecurityHeaders", {
      securityHeadersBehavior: {
        strictTransportSecurity: {
          accessControlMaxAge: cdk.Duration.days(365),
          includeSubdomains: true,
          preload: true,
          override: true,
        },
        contentTypeOptions: { override: true },
        frameOptions: { frameOption: cloudfront.HeadersFrameOption.DENY, override: true },
        referrerPolicy: {
          referrerPolicy: cloudfront.HeadersReferrerPolicy.STRICT_ORIGIN_WHEN_CROSS_ORIGIN,
          override: true,
        },
        contentSecurityPolicy: {
          // script-src 'self' (no inline/eval) is the load-bearing control — the
          // whole token model assumes no XSS. object-src 'none' kills plugin
          // vectors; upgrade-insecure-requests forecloses mixed content.
          // style-src keeps 'unsafe-inline' because Radix/sonner set inline
          // style *attributes*, which CSP nonces/hashes can't cover; this does
          // not loosen scripts. (No SRI: every script is same-origin from the
          // OAC-locked S3 origin — if that origin is compromised, so is the HTML.)
          contentSecurityPolicy:
            "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'; upgrade-insecure-requests",
          override: true,
        },
      },
      // The CDK CSP field is enforce-only, so Trusted Types is staged here in
      // Report-Only first (surfacing any dependency that writes to a DOM sink)
      // before folding `require-trusted-types-for 'script'` into the enforced
      // CSP above. COOP isolates the browsing-context group (XS-Leaks); the
      // Permissions-Policy denies powerful features and pins WebAuthn to self.
      customHeadersBehavior: {
        customHeaders: [
          {
            header: "Content-Security-Policy-Report-Only",
            value: "require-trusted-types-for 'script'",
            override: true,
          },
          {
            header: "Cross-Origin-Opener-Policy",
            value: "same-origin-allow-popups",
            override: true,
          },
          {
            header: "Permissions-Policy",
            value:
              "camera=(), microphone=(), geolocation=(), payment=(), usb=(), serial=(), hid=(), publickey-credentials-get=(self), publickey-credentials-create=(self)",
            override: true,
          },
        ],
      },
    });

    const distribution = new cloudfront.Distribution(this, "Distribution", {
      domainNames: [host],
      certificate,
      minimumProtocolVersion: cloudfront.SecurityPolicyProtocol.TLS_V1_2_2021,
      httpVersion: cloudfront.HttpVersion.HTTP2_AND_3,
      defaultRootObject: "index.html",
      defaultBehavior: {
        origin: origins.S3BucketOrigin.withOriginAccessControl(spaBucket),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
        responseHeadersPolicy: spaSecurity,
        functionAssociations: [
          { function: spaRewrite, eventType: cloudfront.FunctionEventType.VIEWER_REQUEST },
        ],
      },
      additionalBehaviors: {
        "/api/*": apiBehavior,
        "/oauth/*": apiBehavior,
        // More specific than /oauth/* — wins for the Bearer-authenticated path.
        "/oauth/userinfo": bearerBehavior,
        "/.well-known/*": {
          ...apiBehavior,
          // Honor the origin's Cache-Control (JWKS/discovery set their own)
          // without forwarding Host.
          cachePolicy: wellKnownCachePolicy,
        },
      },
    });

    new s3deploy.BucketDeployment(this, "SpaDeployment", {
      sources: [s3deploy.Source.asset(path.join(dir, "../..", config.spaAssetPath))],
      destinationBucket: spaBucket,
      distribution,
      distributionPaths: ["/*"],
    });

    // Bust the edge cache for the OIDC metadata whenever the Lambda changes.
    // /.well-known/* is cached per the origin's Cache-Control (max-age=3600),
    // and a Lambda-only deploy triggers no other invalidation (the SPA
    // BucketDeployment above only invalidates when the SPA asset changes). So
    // discovery / JWKS could otherwise serve a stale response — e.g. missing
    // CORS headers — for up to an hour after a deploy. Keyed on the Lambda
    // asset hash so it re-runs exactly when those responses can change.
    const lambdaHash = cdk.FileSystem.fingerprint(lambdaAssetPath);
    new cr.AwsCustomResource(this, "WellKnownCacheInvalidation", {
      onUpdate: {
        service: "CloudFront",
        action: "createInvalidation",
        parameters: {
          DistributionId: distribution.distributionId,
          InvalidationBatch: {
            CallerReference: lambdaHash,
            Paths: { Quantity: 1, Items: ["/.well-known/*"] },
          },
        },
        physicalResourceId: cr.PhysicalResourceId.of(`wellknown-${lambdaHash}`),
      },
      installLatestAwsSdk: false,
      policy: cr.AwsCustomResourcePolicy.fromStatements([
        new iam.PolicyStatement({
          actions: ["cloudfront:CreateInvalidation"],
          resources: [
            `arn:aws:cloudfront::${this.account}:distribution/${distribution.distributionId}`,
          ],
        }),
      ]),
    });

    // --- DNS: point the zone apex at CloudFront ---
    const recordTarget = route53.RecordTarget.fromAlias(
      new targets.CloudFrontTarget(distribution),
    );
    new route53.ARecord(this, "AliasA", { zone: props.hostedZone, target: recordTarget });
    new route53.AaaaRecord(this, "AliasAaaa", { zone: props.hostedZone, target: recordTarget });

    new cdk.CfnOutput(this, "Issuer", { value: issuerUrl(config) });
    new cdk.CfnOutput(this, "DistributionDomain", { value: distribution.distributionDomainName });
  }
}
